apiVersion: apps/v1
kind: Deployment
metadata:
  name: bloodbank-frontend
  namespace: bloodbank
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bloodbank-frontend
  template:
    metadata:
      labels:
        app: bloodbank-frontend
    spec:
      containers:
      - name: frontend
        image: IMAGE_PREFIX_PLACEHOLDER/bloodbank-frontend:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: bloodbank-frontend
  namespace: bloodbank
spec:
  selector:
    app: bloodbank-frontend
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
